# Generated by Django 6.0.2 on 2026-02-18 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cadastral_number', models.CharField(blank=True, max_length=255, verbose_name='Кадастровый номер')),
                ('customer', models.CharField(max_length=500, verbose_name='Заказчик')),
                ('contract', models.CharField(max_length=255, verbose_name='Договор')),
                ('newspaper', models.CharField(max_length=500, verbose_name='Газета')),
                ('issue_date', models.DateField(blank=True, null=True, verbose_name='Дата выпуска')),
                ('approval_date', models.DateField(blank=True, null=True, verbose_name='Дата согласования')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Извещение',
                'verbose_name_plural': 'Извещения',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NoticeAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(verbose_name='Адрес')),
                ('fias_id', models.CharField(blank=True, max_length=36, verbose_name='ФИАС ID')),
                ('region', models.CharField(blank=True, max_length=255, verbose_name='Регион')),
                ('city', models.CharField(blank=True, max_length=255, verbose_name='Город')),
                ('street', models.CharField(blank=True, max_length=255, verbose_name='Улица')),
                ('house', models.CharField(blank=True, max_length=50, verbose_name='Дом')),
                ('notice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='notices.notice')),
            ],
            options={
                'verbose_name': 'Адрес извещения',
                'verbose_name_plural': 'Адреса извещений',
            },
        ),
    ]
