# Generated by Django 6.0.2 on 2026-02-18 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notice',
            name='cadastral_number',
        ),
        migrations.RemoveField(
            model_name='notice',
            name='contract',
        ),
        migrations.RemoveField(
            model_name='notice',
            name='customer',
        ),
        migrations.CreateModel(
            name='NoticeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(blank=True, verbose_name='Адрес')),
                ('fias_id', models.CharField(blank=True, max_length=36, verbose_name='ФИАС ID')),
                ('region', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=255)),
                ('street', models.CharField(blank=True, max_length=255)),
                ('house', models.CharField(blank=True, max_length=50)),
                ('cadastral_number', models.CharField(blank=True, max_length=255, verbose_name='Кадастровый номер')),
                ('customer', models.CharField(blank=True, max_length=500, verbose_name='Заказчик')),
                ('contract', models.CharField(blank=True, max_length=255, verbose_name='Договор')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('notice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='notices.notice')),
            ],
            options={
                'verbose_name': 'Объект извещения',
                'verbose_name_plural': 'Объекты извещения',
                'ordering': ['order', 'pk'],
            },
        ),
        migrations.DeleteModel(
            name='NoticeAddress',
        ),
    ]
