# Generated by Django 6.0.2 on 2026-02-18 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0002_remove_notice_cadastral_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='newspaper',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Газета'),
        ),
        migrations.AlterField(
            model_name='noticeitem',
            name='fias_id',
            field=models.CharField(blank=True, max_length=36),
        ),
        migrations.AlterField(
            model_name='noticeitem',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
